const constant = {
  ADD_USER: 'ADD_USER',
  GET_USERID: 'GET_USERID',
  UPDATE_USER: 'UPDATE_USER',
  REMOVE_USER: 'REMOVE_USER',
  FETCH_USER: 'FETCH_USER',
  ADD_ACCESS_TOKEN: 'ADD_ACCESS_TOKEN',
  REMOVE_ACCESS_TOKEN: 'REMOVE_ACCESS_TOKEN',

  ADD_LOCATION: 'ADD_LOCATION',

  // Admin constants
  ADD_CATEGORY: 'ADD_CATEGORY',
  SAVE_CATEGORY: 'SAVE_CATEGORY',

  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  SHOW_SUGGESTIONS_CATEGORY: 'SHOW_SUGGESTIONS_CATEGORY',

  REMOVE_CATEGORY: 'REMOVE_CATEGORY',
  REMOVE_COURIER: 'REMOVE_COURIER',
  REMOVE_MERCHANT: 'REMOVE_MERCHANT',

  LIST_CATEGORY: 'LIST_CATEGORY',
  LIST_MERCHANTS: 'LIST_MERCHANTS',
  LIST_COURIERS: 'LIST_COURIERS',

  COUNT_MERCHANT_PRODUCT: 'COUNT_MERCHANT_PRODUCT',
  COUNT_PRODUCT: 'COUNT_PRODUCT',
  COUNT_USERS: 'COUNT_USERS',
  COUNT_MERCHANT: 'COUNT_MERCHANT',
  PRODUCT_SOLD: 'PRODUCT_SOLD',
  TOTAL_EARNING: 'TOTAL_EARNING',

  // Cart Constants
  ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
  UPDATE_CART: 'UPDATE_CART',
  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
  LIST_CART: 'LIST_CART',
  EMPTY_CART: 'EMPTY_CART',

  // Courier Constants
  LIST_COURIERS: 'LIST_COURIERS',
  ADD_COURIERS: 'ADD_COURIERS',
  GET_COURIER: 'GET_COURIER',
  GET_COURIER_USERID: 'GET_COURIER_USERID',

  // Orders Constants
  ADD_ORDERS: 'ADD_ORDERS',
  GET_CUSTOMER_ORDERS: 'GET_CUSTOMER_ORDERS',

  ADD_ORDER_ITEM_DETAILS: 'ADD_ORDER_ITEM_DETAILS',

  // General Purpose
  ADD_ERROR: 'ADD_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
  CLEAR_ALL_ERROR: 'CLEAR_ALL_ERROR',
  FETCHING: 'FETCHING',
  DONE_FETCHING: 'DONE_FETCHING',

  LIST_PRODUCTS: 'LIST_PRODUCTS',
  ADD_PRODUCTS: 'ADD_PRODUCTS',
  ADD_ORDER_ITEM: 'ADD_ORDER_ITEM',
  CLEAR_ORDER_ITEMS: 'CLEAR_ORDER_ITEMS',
  GET_STATES: 'GET_STATES',

  // Merchant
  GET_MERCHANT: 'GET_MERCHANT',
  GET_MERCHANTORDERS: 'GET_MERCHANTORDERS',
  VIEWORDERDETAILS: 'VIEWORDERDETAILS',
  UPDATE_ORDER_ITEM_STATUS: 'UPDATE_ORDER_ITEM_STATUS',
};

export default constant;
