development:
  dialect: "mysql"
  # database: "one_city_mart_development"
  # host: {{envOr "DATABASE_HOST" "localhost"}}
  # port: {{envOr "DATABASE_PORT" "3306"}}
  # user: {{envOr "DATABASE_USER" "root"}}
  url: "mysql://{{envOr "DATABASE_USER" "root"}}:{{envOr "DATABASE_PASSWORD" ""}}@({{envOr "DATABASE_HOST" "localhost"}}:{{envOr "DATABASE_PORT" "3306"}})/one_city_mart_development?parseTime=true&multiStatements=true&readTimeout=0"
  # password: {{envOr "DATABASE_PASSWORD" "onecitymate"}}

test:
  dialect: "mysql"
  #
  # You can use a single URL string for the same configuration:
  #
  #url: "mysql://root:root@(localhost:3306)/one_city_mart_test?parseTime=true&multiStatements=true&readTimeout=3s"
  #
  # Note that if you use `url`, other configurations are silently ignored.
  # In this case, the URL must contain all required connection parameters.
  #
  database: "one_city_mart_test"
  host: {{envOr "DATABASE_HOST" "localhost"}}
  port: {{envOr "DATABASE_PORT" "3306"}}
  user: {{envOr "DATABASE_USER" "root"}}
  password: {{envOr "DATABASE_PASSWORD" "onecitymate"}}

production:
  #
  # You can also use environmental variables to override values in this config.
  #
  #url: {{envOr "DATABASE_URL" "mysql://root:root@(localhost:3306)/one_city_mart_production?parseTime=true&multiStatements=true&readTimeout=3s"}}
  #
  dialect: "mysql"
  database: "one_city_mart_production"
  host: {{envOr "DATABASE_HOST" "localhost"}}
  port: {{envOr "DATABASE_PORT" "3306"}}
  user: {{envOr "DATABASE_USER" "root"}}
  password: {{envOr "DATABASE_PASSWORD" "onecitymate"}}
  #
  # And you can also override connection parameters by setting it under options.
  #
  #options:
  #  parseTime: true
  #  multiStatements: true
  #  readTimeout: 3s
  #  encoding: "utf8mb4_general_ci"
  #
  # CAUTION!
  #   `parseTime` and` multiStatements` must be set to `true` to work properly.
  #   If you are not sure, do not change (or set) these values.
